version: "3.7"
services:
  runs:
    container_name: runs
    build: .
    env_file:
      - ".env.docker"
    healthcheck:
      test: "curl localhost:8000/"
      interval: "60s"
      timeout: "3s"
      start_period: "5s"
      retries: 3
    ports:
      - "8000:8000"
    volumes:
      - .:/opt/
      - /var/log:/var/log/
    networks:
      - runs-net
    depends_on:
      - redis
    restart: unless-stopped
    stop_grace_period: 3s

  runs-worker:
    container_name: runs-worker
    build: .
    command: bash worker.sh docker
    env_file:
      - ".env.docker"
    volumes:
      - .:/opt/
    networks:
      - runs-net
    depends_on:
      - redis
      - runs
    restart: unless-stopped
    stop_grace_period: 3s

  redis:
    container_name: redis
    image: redis:5.0.4-stretch
    command: ["redis-server", "--appendonly", "yes"]
    hostname: redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - runs-net
    restart: unless-stopped
    stop_grace_period: 3s

networks:
  runs-net:

volumes:
  redis-data: {}
